# Generated by Django 3.2 on 2021-04-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isin", models.CharField(max_length=12)),
                (
                    "limit_price",
                    models.DecimalField(decimal_places=2, max_digits=19, null=True),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4
                    ),
                ),
                ("valid_until", models.PositiveIntegerField()),
            ],
        )
    ]
